#!usr/bin/env python3.9

# SCRIPT GOAL: CREATE A "USER CREATION" SCRIPT THAT CAN BE 
# USED WITH OTHER PROGRAMS. IT WILL INCLUDE A WAY FOR USERS
# TO SIGNUP AND/OR LOGIN IF THEY ALREADY HAVE AN ACCOUNT. 
# ONCE THEY SIGN UP, THEIR INFO WILL BE INSERTED INTO THE 
# DATABASE'S 'USERS' TABLE (OR WHATEVER TABLE YOU WANT)
# THEN TO LOGIN, THERE WILL BE A FORM ASKING FOR THE 
# USERS EMAIL (AND/OR) THEIR USERNAME + THEIR PASSWORD. 
# THEN, THE SCRIPT WILL RUN A QUERY THAT SEARCHES THE 
# DATABASE TO CONFIRM THAT THE USERNAME/EMAIL CORRESPONDS
# TO THE USER IN OUR DATABASE. 

import mysql.connector as sql 
import sqlalchemy 
# TODO: CREATE A USER LOGIN 












# USING THEIR FIRST NAME, LAST NAME, EMAIL ADDRESS, 
# PASSWORD, 