# TODO: CREATE PASSWORD GENERATOR

import PySimpleGUI as sg
import hashlib

"""
THIS SCRIPT WILL CREATE A SECURE LOGIN FOR MY SCRIPTS WITHOUT HAVING TO INCLUDE MY PASSWORD IN THE PROGRAM. CREATE A SHA1(sh256 or higher) HASH CODE FOR MY PASSWORD USING THE GUI. THEN JUST PASTE IT INTO A VARIABLE IN FINAL PROGRAM.

### 5 STEPS TO FOLLOW!!!

1. Choose a password
2. Generate a hash code for chosen password by running program and entering 'gui' as password
3. Type password into GUI
4. copy and paste hash code Window GUI into variable named login_password_hash
5. Run program and test login
"""

# USE THIS GUI TO GET PASSWORDS HASH CODE
def HashGeneratorGUI():

    layout = [
        [sg.T('Password Hash Generator',size=(30,1), font='Any 15')],
        [sg.T('Password'), sg.In(key='-PASSWORD-')],
        [sg.T('SHA Hash'), sg.In('', size=(40,1), key='-HASH-')]
        ]

    window = sg.Window('SHA Generator', layout, auto_size_text=False, default_element_size=(10,1), text_justification='r', return_keyboard_events=True, grab_anywhere=False)

    # create while loop

    while True:
        event, values = window.read()
        if event == sg.WIN_CLOSED:
            exit(69)

        password = values['-PASSWORD-']
        try:
            password_utf = password.encode('utf-8')
            sha256hash = hashlib.sha256()
            sha256hash.update(password_utf)
            password_hash = sha256hash.hexdigest()
            window['-HASH-'].update(password_hash)
        except:
            pass

HashGeneratorGUI()
#---------paste this code into your program / script---------#
# determine if a password matches the secret password by
# comparing SHA256 hash codes.

def PasswordMatches(password, hash):
    password_utf = password.encode('utf-8')
    sha256hash = hashlib.sha256()
    sha256hash.update(password_utf)
    password_hash = sha256hash.hexdigest()
    if password_hash == hash:
        return True
    else:
        return False

# this is where you copy and paste the hash generated by
# the gui window
login_password_hash = 'ac6bd1a2caf560356daef1f1de5fd97b8f464b3059f442904a19c92f8fd24282 '
password = sg.popup_get_text('Password', password_char='*')

if password == 'gui':     # REMOVE WHEN PASTING INTO PROGRAM
    HashGeneratorGUI()    # REMOVE WHEN PASTING INTO PROGRAM
    exit(69)              # REMOVE WHEN PASTING INTO PROGRAM
if PasswordMatches(password, login_password_hash):
    print('LOGIN SUCCESSFUL')
else:
    print('login FAILED!!')
